sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1  
before_install:
  - openssl aes-256-cbc -K $encrypted_36d727399aa9_key -iv $encrypted_36d727399aa9_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-8ks-254815
  - gcloud set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t andrey1961/react-test -f ./client/Dockerfile.dev

script:
  - docker run andrey1961/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    